# Generated by Django 5.0.3 on 2024-12-03 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dieselConsumed', '0002_tenant_generatorusage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneratorUsage',
            new_name='DailyRecord',
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='dieselConsumed.tenant')),
            ],
        ),
    ]
